system:
    picard: #fill in
workflow:
    threads: 4
    output: syn4932524
    paired: True
samtofastq:
sailfish:
    referenceID: syn5004897
    index: #fill in
    output: syn4932524
#    metricsTable: syn2809454
    options: --biasCorrect --numBootstraps 100 --useVBOpt -l ISR
    annotations:
        fileType: quantitation
        normalized: TPM
        summaryLevel: transcript



